version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: wordpassr
       MYSQL_DATABASE: wordpress
       MYSQL_USER: worduser
       MYSQL_PASSWORD: wordpass

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: worduser
       WORDPRESS_DB_PASSWORD: wordpass
volumes:
    db_data:
